apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-01
  namespace: webserver
  labels:
    app: web-server 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1-alpine
        ports:
        - containerPort: 80
  
